services:
  - type: web
    name: websale
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn Websale.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
